#!/bin/bash

timeout=1200
while getopts "t:h" opt;
do
  case $opt in
    t)
      timeout=$OPTARG
      ;;
    h)
      echo "Usage:"
      echo "$0 [-t timeout] image-name container-name [options for container]"
      echo "\t\t timeout: wait for timeout seconds, default 900"
      exit 0
      ;;
  esac
done

shift $((OPTIND-1))
image=$1
name=$2
shift 2
#echo $@
docker pull $image

# clean up any old instances

docker rm -f $name > /dev/null 2>&1

set -e
docker run -d --privileged --name $name $image --trace $@
SECONDS=0
last_uptime=0
echo "Waiting for $name to become healthy"
set +e
while [ $SECONDS -lt $timeout -a "$health" != "healthy" ]
do
  sleep 2
  echo -n "."
  health=$(docker inspect --format '{{.State.Health.Status}}' $name)
  if [ $(( SECONDS - last_uptime )) -ge 120 ]
  then
    echo "$name is $health after $SECONDS seconds"
    last_uptime=$SECONDS
  fi
  #status=$(docker inspect --format '{{.State.Status}}' $name)
  #[ "$status" == 'running' ]
done

echo "\n"
if [ $health = "healthy" ]
then
  echo -e "\e[32m$name became healthy in $SECONDS seconds\e[0m"
else
  echo -e "\e[31m$name failed to become healthy after $SECONDS seconds\e[0m"
  false
fi
